package com.lcs.tele.facility.hibernate.model;
// Generated 2017-2-23 11:42:54 by Hibernate Tools 3.6.0.Final

import java.util.Date;

/**
 * UserInfo generated by hbm2java
 */
public class UserInfo implements java.io.Serializable {

	private Integer id;
	private String userName;
	private String password;
	private Date createTime;
	private Date lstTime;

	public UserInfo() {
	}

	public UserInfo(String userName, String password, Date createTime, Date lstTime) {
		this.userName = userName;
		this.password = password;
		this.createTime = createTime;
		this.lstTime = lstTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getLstTime() {
		return this.lstTime;
	}

	public void setLstTime(Date lstTime) {
		this.lstTime = lstTime;
	}

}
